### ISSUE TITLE
java.lang.NoClassDefFoundError: net/bdew/lib/crafting/RecipeMatcher in BloodMagic

### ISSUE THREAD

**Issue by miiichael** [bdew/covers#1]
My joy at finding a 1.8 microblock mod was slightly dampened when my server (basically FTBUnstable1.8 with a few extras thrown in) no longer successfully started once I added covers (and bdlib) to it. :stuck_out_tongue:

I realise that there's a 50% chance this is in fact a BloodMagic bug (in which case I apologise for guessing incorrectly! My punishment will be having to report the same bug twice), however someone had to be first...

I have attached the resulting [fml-server-latest.log](https://github.com/bdew/covers/files/167348/fml-server-latest.log.txt) for your perusal. Thanks!

**Comment by bdew** [comment]
Update BDLib to build 28 or higher.

http://minecraft.curseforge.com/projects/bdlib/files
