### ISSUE TITLE
Grass turns white when cut up

### ISSUE THREAD

**Issue by FnordMan** [bdew/covers#10]
Attempting to make some grass covers only the problem is the moment I cut a grass block with the saw the resulting bits turn white, both in inventory and when placed in the world. 

Is this something fixable?

**Comment by bdew** [comment]
Hm... might be fixable, but would require some changes to MCMP i think. I'll look into it when i get some spare time.

**Comment by bdew** [comment]
Looks like @amadornes already implemented the needed stuff in MCMP but it's not in the latest release build. 

amadornes/MCMultiPart@5c906bc61830603e367b8e711712040e2375d27a

Hopefully it will allow me to fix color for grass and some other blocks when it's released.

**Comment by bubblesayoyo** [comment]
Also is happening with Forestry leaves. Not sure if you want to include these in there anyway, but turns them all white as well.

**Comment by bdew** [comment]
Yeah it will be a problem for any block that has variable hue. Without that change in MCMP there is no way to pass the color to the rendering system so it defaults to white/gray.

**Comment by amadornes** [comment]
I'm hoping to push out 2.0.0 in the next couple of weeks and that's one of the biggest features it includes. So soon :)

**Comment by bdew** [comment]
Should be fixed in next build. Requires MCMP >= 1.3.

**Comment by amadornes** [comment]
Yep! 2.0.0 will come later on with all the new big features and changes. I didn't think it was worth making everyone wait :P
