### ISSUE TITLE
Deleting manually added covers

### ISSUE THREAD

**Issue by bubblesayoyo** [bdew/covers#11]
I feel like you hate me...

If you have a cover/micropart placed in the world, and you delete it from the config (or the whole config) you get the following crash.

example: I tested the botania mana spreader and forestry leaves.  after removing, got the crash

[CRASH](http://pastebin.com/xHMmzyZJ)

**Comment by bdew** [comment]
Should be fixed in next build. Parts with unknown materials will convert to stone when loaded.
