### ISSUE TITLE
Game Crash With Chisel

### ISSUE THREAD

**Issue by ChloeDawn** [bdew/covers#12]
Game crashes during startup when Covers attempts to check disabled Chisel blocks.
I have Invar blocks disabled (`B:invar=false`) in my `chisel.cfg`, among other various blocks.

Is there maybe a way you could check against the Chisel config and only try to register the blocks that are enabled for that instance of the game? Or maybe have it ignore any blocks that resolve to Air?

Crash report: **[pastebin.com/A9XZAuzN](http://pastebin.com/A9XZAuzN)**

Chisel config (for reference): **[pastebin.com/fdSqQvRz](http://pastebin.com/fdSqQvRz)**

Mod version: **[0.4.0.11](https://minecraft.curseforge.com/projects/simple-covers/files/2337692)**
Chisel version: **[0.0.6.53](https://minecraft.curseforge.com/projects/chisel/files/2337360)**
Minecraft version: **[1.10.2](https://mojang.com/2016/06/minecraft-1101/)**
Forge version: **[12.18.2.2107](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.2.2107/forge-1.10.2-12.18.2.2107-changelog.txt)**

**EDIT:**
Changed links from Hastebin to Pastebin because for some reason I am now getting an `ERR_NAME_NOT_RESOLVED` in Chrome for the domain and I'm not sure if it's just on my end or not.

**Comment by bdew** [comment]
Oops. I was moving stuff around in intialization code and forgot that this lookup throws and exception for missing blocks. Should be fixed in next build.
