### ISSUE TITLE
Crash w/ MCMultipart 1.3.0

### ISSUE THREAD

**Issue by FnordMan** [bdew/covers#13]
Simple covers version: 0.4.0.9

Steps to reproduce:
Put a stone brick cover on side of ultimate logistical tranporter (Mekanism), put lever on said stone brick cover  (optional? flip lever on/off), break lever, observe crash. 

Should crash every time you look at the block, which means i've got to MCedit my save as I can't get into the world now. 

Crash report:
[crash-2016-10-31_13.41.40-client.txt](https://github.com/bdew/covers/files/562582/crash-2016-10-31_13.41.40-client.txt)

**Comment by bdew** [comment]
The new MCMP 1.3 broke some stuff. Should be fixed in this build: https://minecraft.curseforge.com/projects/simple-covers/files/2340870
