### ISSUE TITLE
[Feature Request] Please make your mod compatible with Railcrafts Quarried Stone

### ISSUE THREAD

**Issue by jk1895** [bdew/covers#14]
This would be great. I like this block so much but it's hard to build with it in 1.10.2.
https://ftbwiki.org/Quarried_Stone
Thank you very much.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
