### ISSUE TITLE
Hollow covers visual glitch?

### ISSUE THREAD

**Issue by killerscorpion** [bdew/covers#16]
This is a similar problem to #15. Though, this issue is more of just a visual glitch. The pictures says it all, looks like the Mekanism cables get "cutoff" when put through a hollow cover. Currently using SC version 0.4.1.14 with forge 12.18.3.2185. 
![2016-12-11_13 25 06](https://cloud.githubusercontent.com/assets/10732882/21083492/a71c7f82-bfa6-11e6-8010-fa6f4df6a087.png)
![2016-12-11_13 30 15](https://cloud.githubusercontent.com/assets/10732882/21083494/aa5d21e2-bfa6-11e6-97b2-d513473b4be9.png)

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
