### ISSUE TITLE
Missing blockcrack particles

### ISSUE THREAD

**Issue by MarikCZ** [bdew/covers#17]
I mine one microblock, but with black and purple blockcrack particles. I say "WTF? So, I remove it!", but after restart I can see black and purple blockcrack particles anywhere. I try to reset folder with the modpack, but nothing matter.
It annoying me. How I can fix it?
Thanks for response!

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
