### ISSUE TITLE
Is it possible to add more blocks for Simple Covers? 

### ISSUE THREAD

**Issue by crosenquist** [bdew/covers#18]
ProjectRed and its microblock functionality have a config file that allows users to add more blocks to the list of available microblocks. Unfortunately, I don't see a config file within the SimpleCovers config folder that would allow for this.

Am I missing something, or is this simply not possible to do? If it's not possible, is it a planned feature?

**Comment by bdew** [comment]
Make a file named \<whatever>.cfg in the config folder, and put them there [formatted like that](https://github.com/bdew/covers/blob/mc1.10.2/resources/assets/covers/config/materials_minecraft.cfg).

Added: Also if you make some good lists for any common mod, please submit them here, i'll be happy to include them in the default distribution.

**Comment by crosenquist** [comment]
Woah! Thank you for the insanely speedy reply and for the help! It worked!

I had spent all Thursday night identifying which blocks I wanted to make microblocks with ProjectRed from the "All The Mods". In the end, I parsed through some 3,000 individual blocks and then formatted them all in a single clean sweep.  However, I did all that work only to discover that its config file is not currently working with 1.10.2.

Seeing that this works with Simple Covers, I'm going to convert my previous config file from Project Red and see what the results are. If they turn out positive I'll attach them here for the community to use. The more microblocks the merrier! 

Thanks again bdew! Totally saved the day!

**Comment by crosenquist** [comment]
I'm going through and isolating individual configuration files at the moment to see which specific mods cause problems when they have blocks converted into microblocks. However, I have discovered that Simple Covers is not able to read block names or mod names that contain either periods "." or dashes "-". When a configuration file exists where a block or mod name contains either of these two characters the client will crash.

**Unrecognizable Mods:**
1. Forestry
2. Projectred-Illumination
3. Techreborn

**Forestry:**
The periods "." within the individual block names are preventing blocks such as logs, planks, and leaves from being created into microblocks.
```
if HaveMod forestry <<

AddMaterial B:forestry:bogEarth@0
AddMaterial B:forestry:humus@0
AddMaterial B:forestry:resourceStorage@0
AddMaterial B:forestry:resourceStorage@1
AddMaterial B:forestry:resourceStorage@2
AddMaterial B:forestry:resourceStorage@3
AddMaterial B:forestry:logs\.0@0
AddMaterial B:forestry:logs.0@1
AddMaterial B:forestry:logs.0@2
AddMaterial B:forestry:logs.0@3
AddMaterial B:forestry:logs.1@0
AddMaterial B:forestry:logs.1@1
AddMaterial B:forestry:logs.1@2
AddMaterial B:forestry:logs.1@3
AddMaterial B:forestry:logs.2@0
AddMaterial B:forestry:logs.2@1
AddMaterial B:forestry:logs.2@2
AddMaterial B:forestry:logs.2@3
AddMaterial B:forestry:logs.3@0
AddMaterial B:forestry:logs.3@1
AddMaterial B:forestry:logs.3@2
AddMaterial B:forestry:logs.3@3
AddMaterial B:forestry:logs.4@0
AddMaterial B:forestry:logs.4@1
AddMaterial B:forestry:logs.4@2
AddMaterial B:forestry:logs.4@3
AddMaterial B:forestry:logs.5@0
AddMaterial B:forestry:logs.5@1
AddMaterial B:forestry:logs.5@2
AddMaterial B:forestry:logs.5@3
AddMaterial B:forestry:logs.6@0
AddMaterial B:forestry:logs.6@1
AddMaterial B:forestry:logs.6@2
AddMaterial B:forestry:logs.6@3
AddMaterial B:forestry:logs.7@0
AddMaterial B:forestry:planks.0@0
AddMaterial B:forestry:planks.0@1
AddMaterial B:forestry:planks.0@2
AddMaterial B:forestry:planks.0@3
AddMaterial B:forestry:planks.0@4
AddMaterial B:forestry:planks.0@5
AddMaterial B:forestry:planks.0@6
AddMaterial B:forestry:planks.0@7
AddMaterial B:forestry:planks.0@8
AddMaterial B:forestry:planks.0@9
AddMaterial B:forestry:planks.0@10
AddMaterial B:forestry:planks.0@11
AddMaterial B:forestry:planks.0@12
AddMaterial B:forestry:planks.0@13
AddMaterial B:forestry:planks.0@14
AddMaterial B:forestry:planks.0@15
AddMaterial B:forestry:planks.1@0
AddMaterial B:forestry:planks.1@1
AddMaterial B:forestry:planks.1@2
AddMaterial B:forestry:planks.1@3
AddMaterial B:forestry:planks.1@4
AddMaterial B:forestry:planks.1@5
AddMaterial B:forestry:planks.1@6
AddMaterial B:forestry:planks.1@7
AddMaterial B:forestry:planks.1@8
AddMaterial B:forestry:planks.1@9
AddMaterial B:forestry:planks.1@10
AddMaterial B:forestry:planks.1@11
AddMaterial B:forestry:planks.1@12
AddMaterial B:forestry:leaves@0
AddMaterial B:forestry:leaves.decorative.0@0
AddMaterial B:forestry:leaves.decorative.0@1
AddMaterial B:forestry:leaves.decorative.0@2
AddMaterial B:forestry:leaves.decorative.0@3
AddMaterial B:forestry:leaves.decorative.0@4
AddMaterial B:forestry:leaves.decorative.0@5
AddMaterial B:forestry:leaves.decorative.0@6
AddMaterial B:forestry:leaves.decorative.0@7
AddMaterial B:forestry:leaves.decorative.0@8
AddMaterial B:forestry:leaves.decorative.0@9
AddMaterial B:forestry:leaves.decorative.0@10
AddMaterial B:forestry:leaves.decorative.0@11
AddMaterial B:forestry:leaves.decorative.0@12
AddMaterial B:forestry:leaves.decorative.0@13
AddMaterial B:forestry:leaves.decorative.0@14
AddMaterial B:forestry:leaves.decorative.0@15
AddMaterial B:forestry:leaves.decorative.1@0
AddMaterial B:forestry:leaves.decorative.1@1
AddMaterial B:forestry:leaves.decorative.1@2
AddMaterial B:forestry:leaves.decorative.1@3
AddMaterial B:forestry:leaves.decorative.1@4
AddMaterial B:forestry:leaves.decorative.1@5
AddMaterial B:forestry:leaves.decorative.1@6
AddMaterial B:forestry:leaves.decorative.1@7
AddMaterial B:forestry:leaves.decorative.1@8
AddMaterial B:forestry:leaves.decorative.1@9
AddMaterial B:forestry:leaves.decorative.1@10
AddMaterial B:forestry:leaves.decorative.1@11
AddMaterial B:forestry:leaves.decorative.1@12
AddMaterial B:forestry:leaves.decorative.1@13
AddMaterial B:forestry:leaves.decorative.1@14
AddMaterial B:forestry:leaves.decorative.1@15
AddMaterial B:forestry:leaves.decorative.2@0
AddMaterial B:forestry:leaves.decorative.2@1
AddMaterial B:forestry:leaves.decorative.2@2
AddMaterial B:forestry:pile_dirt@0
AddMaterial B:forestry:pile_ash@0
AddMaterial B:forestry:greenhouse.plain@0
AddMaterial B:forestry:greenhouse.glass@0

>>
```

**Projectred-Illumination:**
The dash "-" in the mod name is preventing Simple Covers from incorporating the configuration file into the mod. Because the crash report only reads up until the mod name in the header of the configuration file I can not verify if it can parse dashes within block names. However, I believe it's safe to assume that it cannot.
```
if HaveMod projectred-illumination <<

AddMaterial B:projectred-illumination:lamp@0
AddMaterial B:projectred-illumination:lamp@1
AddMaterial B:projectred-illumination:lamp@2
AddMaterial B:projectred-illumination:lamp@3
AddMaterial B:projectred-illumination:lamp@4
AddMaterial B:projectred-illumination:lamp@5
AddMaterial B:projectred-illumination:lamp@6
AddMaterial B:projectred-illumination:lamp@7
AddMaterial B:projectred-illumination:lamp@8
AddMaterial B:projectred-illumination:lamp@9
AddMaterial B:projectred-illumination:lamp@10
AddMaterial B:projectred-illumination:lamp@11
AddMaterial B:projectred-illumination:lamp@12
AddMaterial B:projectred-illumination:lamp@13
AddMaterial B:projectred-illumination:lamp@14
AddMaterial B:projectred-illumination:lamp@15
AddMaterial B:projectred-illumination:lamp@16
AddMaterial B:projectred-illumination:lamp@17
AddMaterial B:projectred-illumination:lamp@18
AddMaterial B:projectred-illumination:lamp@19
AddMaterial B:projectred-illumination:lamp@20
AddMaterial B:projectred-illumination:lamp@21
AddMaterial B:projectred-illumination:lamp@22
AddMaterial B:projectred-illumination:lamp@23
AddMaterial B:projectred-illumination:lamp@24
AddMaterial B:projectred-illumination:lamp@25
AddMaterial B:projectred-illumination:lamp@26
AddMaterial B:projectred-illumination:lamp@27
AddMaterial B:projectred-illumination:lamp@28
AddMaterial B:projectred-illumination:lamp@29
AddMaterial B:projectred-illumination:lamp@30
AddMaterial B:projectred-illumination:lamp@31

>>
```

**Techreborn:**
Like Forestry, Techreborn has block names that contain periods ".". 
```
if HaveMod techreborn <<

AddMaterial B:techreborn:techreborn.storage@0
AddMaterial B:techreborn:techreborn.storage@1
AddMaterial B:techreborn:techreborn.storage@2
AddMaterial B:techreborn:techreborn.storage@3
AddMaterial B:techreborn:techreborn.storage@4
AddMaterial B:techreborn:techreborn.storage@5
AddMaterial B:techreborn:techreborn.storage@6
AddMaterial B:techreborn:techreborn.storage@7
AddMaterial B:techreborn:techreborn.storage@8
AddMaterial B:techreborn:techreborn.storage@9
AddMaterial B:techreborn:techreborn.storage@10
AddMaterial B:techreborn:techreborn.storage@11
AddMaterial B:techreborn:techreborn.storage@12
AddMaterial B:techreborn:techreborn.storage@13
AddMaterial B:techreborn:techreborn.storage2@0
AddMaterial B:techreborn:techreborn.storage2@1
AddMaterial B:techreborn:techreborn.storage2@2
AddMaterial B:techreborn:techreborn.storage2@3
AddMaterial B:techreborn:techreborn.storage2@4
AddMaterial B:techreborn:techreborn.storage2@5
AddMaterial B:techreborn:techreborn.storage2@8
AddMaterial B:techreborn:techreborn.storage2@9
AddMaterial B:techreborn:techreborn.machineFrame@0
AddMaterial B:techreborn:techreborn.machineFrame@1
AddMaterial B:techreborn:techreborn.machineFrame@2
AddMaterial B:techreborn:rubberLog@0
AddMaterial B:techreborn:rubberPlanks@0
AddMaterial B:techreborn:rubberLeaves@0
AddMaterial B:techreborn:reinforcedglass@0
AddMaterial B:techreborn:batBox@0

>>
```

**Comment by crosenquist** [comment]
I've just completed testing the following configuration files. 

These configuration files have been based on my personal tastes, as a result, not every configuration file will include every block from a particular mod. That being said, there should be just about 3,000 extra blocks contained within these files, which when multiplied by the number of microblock forms (16) brings us to about 48,000 placeable blocks just from these configuration files alone. 

If there exists a solution for the current issue that is preventing the creation of microblocks whose block and mod names contain characters such as periods and dashes, then we'll be able to see the addition of mods like Forestry which has a lot to offer a mod like this. 

_Note: github wouldn't allow me to upload a zip folder containing the .cfg files, so I had to convert them to .txt files._

**Configuration Files:**
[materials_abyssalcraft.txt](https://github.com/bdew/covers/files/785521/materials_abyssalcraft.txt)
[materials_actuallyadditions.txt](https://github.com/bdew/covers/files/785525/materials_actuallyadditions.txt)
[materials_armorplus.txt](https://github.com/bdew/covers/files/785520/materials_armorplus.txt)
[materials_bigreactors.txt](https://github.com/bdew/covers/files/785522/materials_bigreactors.txt)
[materials_biomesoplenty.txt](https://github.com/bdew/covers/files/785524/materials_biomesoplenty.txt)
[materials_bloodmagic.txt](https://github.com/bdew/covers/files/785523/materials_bloodmagic.txt)
[materials_bookshelf.txt](https://github.com/bdew/covers/files/785526/materials_bookshelf.txt)
[materials_calculator.txt](https://github.com/bdew/covers/files/785531/materials_calculator.txt)
[materials_correlated.txt](https://github.com/bdew/covers/files/785527/materials_correlated.txt)
[materials_crossroads.txt](https://github.com/bdew/covers/files/785530/materials_crossroads.txt)
[materials_cyberware.txt](https://github.com/bdew/covers/files/785529/materials_cyberware.txt)
[materials_darkutils.txt](https://github.com/bdew/covers/files/785528/materials_darkutils.txt)
[materials_deepresonance.txt](https://github.com/bdew/covers/files/785532/materials_deepresonance.txt)
[materials_draconicevolution.txt](https://github.com/bdew/covers/files/785533/materials_draconicevolution.txt)
[materials_embers.txt](https://github.com/bdew/covers/files/785534/materials_embers.txt)
[materials_environmentaltech.txt](https://github.com/bdew/covers/files/785535/materials_environmentaltech.txt)
[materials_fluxnetworks.txt](https://github.com/bdew/covers/files/785537/materials_fluxnetworks.txt)
[materials_funkylocomotion.txt](https://github.com/bdew/covers/files/785536/materials_funkylocomotion.txt)
[materials_harvestcraft.txt](https://github.com/bdew/covers/files/785538/materials_harvestcraft.txt)
[materials_ic2.txt](https://github.com/bdew/covers/files/785541/materials_ic2.txt)
[materials_immersiveengineering.txt](https://github.com/bdew/covers/files/785540/materials_immersiveengineering.txt)
[materials_mekanism.txt](https://github.com/bdew/covers/files/785539/materials_mekanism.txt)
[materials_mekanismgenerators.txt](https://github.com/bdew/covers/files/785542/materials_mekanismgenerators.txt)
[materials_mysticalagriculture.txt](https://github.com/bdew/covers/files/785543/materials_mysticalagriculture.txt)
[materials_natura.txt](https://github.com/bdew/covers/files/785544/materials_natura.txt)
[materials_opencomputers.txt](https://github.com/bdew/covers/files/785545/materials_opencomputers.txt)
[materials_psi.txt](https://github.com/bdew/covers/files/785549/materials_psi.txt)
[materials_psionup.txt](https://github.com/bdew/covers/files/785547/materials_psionup.txt)
[materials_quark.txt](https://github.com/bdew/covers/files/785546/materials_quark.txt)
[materials_railcraft.txt](https://github.com/bdew/covers/files/785548/materials_railcraft.txt)
[materials_randomthings.txt](https://github.com/bdew/covers/files/785550/materials_randomthings.txt)
[materials_refinedstorage.txt](https://github.com/bdew/covers/files/785551/materials_refinedstorage.txt)
[materials_refraction.txt](https://github.com/bdew/covers/files/785552/materials_refraction.txt)
[materials_rftools.txt](https://github.com/bdew/covers/files/785554/materials_rftools.txt)
[materials_roots.txt](https://github.com/bdew/covers/files/785553/materials_roots.txt)
[materials_sonarcore.txt](https://github.com/bdew/covers/files/785555/materials_sonarcore.txt)
[materials_stevescarts.txt](https://github.com/bdew/covers/files/785556/materials_stevescarts.txt)
[materials_substratum.txt](https://github.com/bdew/covers/files/785557/materials_substratum.txt)
[materials_tconstruct.txt](https://github.com/bdew/covers/files/785560/materials_tconstruct.txt)
[materials_vitality.txt](https://github.com/bdew/covers/files/785561/materials_vitality.txt)
[materials_wtfcore.txt](https://github.com/bdew/covers/files/785559/materials_wtfcore.txt)
[materials_xreliquary.txt](https://github.com/bdew/covers/files/785558/materials_xreliquary.txt)

**Comment by bdew** [comment]
Awesome work on those files, i'll look through them when i have the time (hopefully later today)

You need to quote the names that have dots in them, e.g.

    AddMaterial B:forestry:"logs.0"@1

**Comment by ghost** [comment]
FYI, I tried out some of the configs posted.  Immersive Engineering and Railcraft both work great but biomesoplenty didn't.  (in 1.10.2)

**Comment by crosenquist** [comment]
I've been away from Minecraft for a couple months. Reinstalling this mod now. I suspect Biomes O' Plenty changed its block registry. After I get things sorted I'll reply with an update about what I found.

**Comment by ghost** [comment]
It was just the modid.  Searched/Replaced biomesoplenty with BiomesOPlenty and it worked like a charm.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Comment by calloatti** [comment]
1.12? I cannot describe with words how much I miss your mod in 1.12...

**Comment by bdew** [comment]
MCMP got completely changed, so i have to rewrite pretty much everything now... it'll be out soon (tm).
