### ISSUE TITLE
[1.10.2] Crash with Covers on LAN

### ISSUE THREAD

**Issue by MokahTGS** [bdew/covers#19]
Got a crash with a LAN player placing a cover:

https://pastebin.com/T6UNeFEy

**Comment by bdew** [comment]
Er... Are you sure you are placing a cover from this mod?

The crash is in FMP code which this mod has nothing to do with...

**Comment by MokahTGS** [comment]
FMP doesn't add covers.  It just adds the way to do it in the code.  I had to add your mod to get the covers in the first place.  Your mod requires FMP to work doesn't it?

**Comment by bdew** [comment]
No, this mod uses MCMP (https://minecraft.curseforge.com/projects/mcmultipart), it's a different API.

FMP was supposed to die with 1.7.10 and then was only ported to 1.10 very recently.

**Comment by MokahTGS** [comment]
This looks like it was an issue caused by Forge Multipart also being installed...not sure how that happened, but I'll close this.
