### ISSUE TITLE
[Suggestion/Question]: Config Options

### ISSUE THREAD

**Issue by Lanse505** [bdew/covers#2]
Hey Bdew o/

I was just wondering for 1.9 with Covers:
1. Should the Config File be Empty?
   Pic: http://puu.sh/ogwvL/ec9b66f289.config
2. Could we possibly get a Config option to only allow one Cover-Type per Block to show up to reduce on JEI Load Lag? (Don't want to result to the nuclear option of using CraftTweaker (Minetweaker for 1.9) to remove stuff from JEI).
3. Awesome Mod! :)

**Comment by Lanse505** [comment]
4 . the example file you linked in Simple Covers CFs Comments isn't working, got a new example link for how to add your own blocks and such?

Pic: http://puu.sh/ogwDN/4cbf97b744.png

**Comment by bdew** [comment]
1. For now, yes, it's the client-side config that currently has no options implemented
2. Planned, but not done yet
3. Thanks :P
4. How is it not working? are you getting any errors/warnings in the log?

Note that additional materials should go into a file named <whatever>.cfg, NOT client.config

**Comment by Lanse505** [comment]
I mean like the example you've got linked produces a:
http://puu.sh/ohNPT/273235a941.jpg

**Comment by bdew** [comment]
Weird, i guess github is messing something up, try this link https://github.com/bdew/covers/blob/mc1.9.0/resources/assets/covers/config/materials.cfg

**Comment by Lanse505** [comment]
Works splendidly! :)
