### ISSUE TITLE
About it NBT tags

### ISSUE THREAD

**Issue by Bernie3852** [bdew/covers#20]
I need to make some recipes of covers' block
what is it's NBT tags?

**Comment by VMan-2002** [comment]
- shape (string): `"face"`, `"strip"`, `"corner"`, `"hollowface"`, `"ghost"`
- size (integer): `1`: cover, `2`: panel, `3`: cover + panel, `4`: slab, `5`: cover + slab, etc
- material (string): example for stone: `"minecraft:stone[variant=stone]"`
Stone Slab: `{shape:"face",size:4,material:"minecraft:stone[variant=stone]"}`


I'm not a developer of this mod but I hope this helps. This reply might be too late though :(

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
