### ISSUE TITLE
[1.10.2] Mekanism cables and pipes

### ISSUE THREAD

**Issue by themechman** [bdew/covers#22]
Running into a problem with the latest release of Mekanism for 1.10.2.

While this appears to be largely cosmetic, there are instances which power stops flowing between mekanism power cables when a hollow plate is installed.

Please let me know what information you need.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
