### ISSUE TITLE
Missing Part Occlusion

### ISSUE THREAD

**Issue by AlgorithmX2** [bdew/covers#3]
Parts should implement IOccludingPart to occlude space; also optionally they should test space occlusion as well, that way you can't place C&B bits and Covers in the same physical space.

Sorry for any derpyness while posting, accidentally posted it before I had typed anything XD

**Comment by bdew** [comment]
I'll add IOccludingPart support.

I'm not sure about checking for occlusion because there are legit use cases where they need to clip each other (and there are provisions in the rendering code for it to not look stupid). I'll play with it and see if i can figure out a reasonable solution.

**Comment by bdew** [comment]
Added INormallyOccludingPart Part in d7c92c2cb02e9b3ac1b5ba7f3209f0344338b082
