### ISSUE TITLE
Display placement grid & allow for FMP-style placement

### ISSUE THREAD

**Issue by ghost** [bdew/covers#4]
It would be nice if there was a grid (like past microblock mods) to see where you can/where you need to click to place a microblock in a certain orientation. It would also be nice if you could increase the size of an already-placed cover/notch/etc by placing the microblock on it (easier understood if you try using FMP).

Also there seems to be a z-fighting issue with the placement visual (I think this should be a little more transparent too).

Lastly, the lighting looks a bit dull.

![](http://i.nentify.me/10MAiE7f.png)

Just some requests, take it or leave it! :) I think they'd improve the mod though.

**Comment by bdew** [comment]
Added an option to change the transparency of the placement preview. Also lighting should be better now.

> It would be nice if there was a grid (like past microblock mods) to see where you can/where you need to click to place a microblock in a certain orientation. 

I'll look in to it at some point as an option, though i honestly think my WYSIWYG preview is better.

>  It would also be nice if you could increase the size of an already-placed cover/notch/etc by placing the microblock on it (easier understood if you try using FMP).

Planned, though it's a bit complicated to get right with the current implementation.

**Comment by ghost** [comment]
Sounds good! And I personally like the combo of WYSIWYG with a grid. It makes it easier to see where you need to click for a certain orientation very quickly without having to guess.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
