### ISSUE TITLE
Chisel + SimpleCovers

### ISSUE THREAD

**Issue by bubblesayoyo** [bdew/covers#8]
Assuming this is just a no-go? I've added the .cfg, and it loads fine, but when I actually make the covers they are just blank, transparent. (they 'show' up, but are clear, non-exsistant)

Anyway, I assume it's just not possible, but I thought I'd drop this here just in case.

**Comment by bdew** [comment]
It should work unless they do something weird like using TESR's. I'll take a look.

**Comment by bubblesayoyo** [comment]
I'm using:

covers-0.4.0.9-mc1.10.2
Chisel-MC1.9.4-0.0.6.51

in case you need that.

**Comment by bdew** [comment]
Looks like chisel needs a small change for this to work, i've submitted a PR to them - Chisel-Team/Chisel#260

**Comment by bdew** [comment]
The PR was accepted, this should work with Simple Covers >= 0.4.0.10 and whatever the next build of Chisel will be.

You will still need to specify a list of blocks in the config. I might make a list and add it to the default config later.

**Comment by bubblesayoyo** [comment]
I've got a complete list so I can get it to you. But I'm running into a problem with a few of things from chisel, specifically:
AddMaterial B:chisel:planks-acacia@0
Doesn't look like covers can take the "-" symbol. Any suggestions? It's also on a few other items other than just wooden planks.

EDIT: Forestry is using "." too, example logs.0, logs.1, etc...

**Comment by bdew** [comment]
You need to quote any names with non-alphanumeric characters. eg. 

> AddMaterial B:chisel:"planks-acacia"@0

**Comment by bubblesayoyo** [comment]
Thanks, I'm working on a pretty big list of mods with all their covers created, I can post them when all done. Is there a way to comment them, so make it a little easier to read?

**Comment by bdew** [comment]
```
// like that (line comment)

/* or like that 
(block comment)
bla bla bla */
```

**Comment by bubblesayoyo** [comment]
Here is covers for chisel:

[chiselCovers](http://pastebin.com/0XJf9Y1J)

Let me know if you want anymore, I can gladly do them.  I'm not sure if you want to 'ship' covers with some defaults. I have a few other mods already done, just trying to test them as best as possible. 

ps. love the fact that glowstone includes light.

any thoughts on connected textures?

**Comment by bdew** [comment]
I'll add it in the next build. I generally want to provide default configs for materials from other mods (as long as they don't look weird/crash), just haven't got the time to make them myself yet.

If you have anymore send them my way :P

> any thoughts on connected textures?

Sadly not possible, or at least i haven't found a way to make it work. Chisel needs stuff implemented on the block object for CTM to work and MCMP doesn't really support that.

**Comment by bubblesayoyo** [comment]
Forestry, currently have the leaves disabled. but here it is:

[forestryCovers](http://pastebin.com/9a4NkQrt)
