### ISSUE TITLE
Covers + ExtraUtils2

### ISSUE THREAD

**Issue by bubblesayoyo** [bdew/covers#9]
Either scrolling across the page in JEI, or when putting the saw + a EU2 block in the crafting table causes crash. This is report of the saw/block combo in side crafting table:

[Crash](http://pastebin.com/vLFZgTXA)

**Comment by bdew** [comment]
I'll look at it tommorow... what block was that?

**Comment by bubblesayoyo** [comment]
Can't remember exactly, maybe one of the glasses? But I think it might be all the EXU2 blocks, because like I said if you scroll over their page in JEI it also crashes with a similar report.

**Comment by bdew** [comment]
Doesn't look fixable on my side, i did open a bug on EU tracker rwtema/extrautilities#1050, maybe they can fix it.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
